const LOGIN = 'LOGIN';//登录
const LOGIN_SUCCEED = 'LOGIN_SUCCEED';//登录成功
const LANGUAGE_CHANGE = 'LANGUAGE_CHANGE';//语言更改
const TO_LANGUAGE_CHANGE = 'TO_LANGUAGE_CHANGE';//通知本地语言修改
const TO_CLOSE_LOGIN_WINDOW = 'TO_CLOSE_LOGIN_WINDOW';//关闭登陆界面
const TO_MINUS_LOGIN_WINDOW = 'TO_MINUS_LOGIN_WINDOW';//最小化登陆界面
const TO_EXIT_SYSTEM = 'TO_EXIT_SYSTEM';//退出系统
const TO_SWITCH_ACCOUNT = 'TO_SWITCH_ACCOUNT';//切换账户
const TO_CHOOSE_FILE = 'TO_CHOOSE_FILE';//切换账户
const TO_DOWNLOAD_FILE = 'TO_DOWNLOAD_FILE';
const TO_UPLOAD_FILE = 'TO_UPLOAD_FILE';

const TO_UPLOAD_SINGLES_FILE = 'TO_UPLOAD_SINGLES_FILE'// 上传单个具体的文件，而不是整个文件夹
const CANCEL_UPLOAD = 'CANCEL_UPLOAD' //取消上传
const UP_LOAD_SINGLES_fILE_ALL = 'UP_LOAD_SINGLES_fILE_ALL' //单个文件列表上传的所有个数
const UP_LOAD_SINGLES_STATES = 'UP_LOAD_SINGLES_STATES' //单个文件上传的状态
const UP_LOAD_SINGLES_File_RECORD = 'UP_LOAD_SINGLES_File_RECORD'//单个文件上传的记录

const GET_OPEN_FILE_NAME = 'GET_OPEN_FILE_NAME' //获得将要上传文件名称
const COVER_UPLOAD = 'COVER_UPLOAD' //覆盖上传
const UP_LOAD_ALL_SUCCESS = 'UP_LOAD_ALL_SUCCESS'//全部上传成功
const UP_LOAD_File_ALL = 'UP_LOAD_File_ALL' //全部文件上传
const UP_LOAD_STATES = 'UP_LOAD_STATES' // 上传状态
const UP_LOAD_File_RECORD = 'UP_LOAD_File_RECORD' //上传文件记录




module.exports = {
    LOGIN,
    LOGIN_SUCCEED,
    LANGUAGE_CHANGE,
    TO_LANGUAGE_CHANGE,
    TO_CLOSE_LOGIN_WINDOW,
    TO_MINUS_LOGIN_WINDOW,
    TO_EXIT_SYSTEM,
    TO_SWITCH_ACCOUNT,
    TO_CHOOSE_FILE,
    TO_DOWNLOAD_FILE,
    TO_UPLOAD_FILE,
    TO_UPLOAD_SINGLES_FILE,
    CANCEL_UPLOAD,
    UP_LOAD_SINGLES_fILE_ALL,
    UP_LOAD_SINGLES_STATES,
    UP_LOAD_SINGLES_File_RECORD,
    GET_OPEN_FILE_NAME,
    COVER_UPLOAD,
    UP_LOAD_ALL_SUCCESS,
    UP_LOAD_File_ALL,
    UP_LOAD_STATES,
    UP_LOAD_File_RECORD
}