 const LOGIN = 'LOGIN';//登录
 const LOGIN_SUCCEED = 'LOGIN_SUCCEED';//登录成功
 const LANGUAGE_CHANGE = 'LANGUAGE_CHANGE';//语言修改
 const TO_LANGUAGE_CHANGE = 'TO_LANGUAGE_CHANGE';//通知本地语言修改
 const TO_CLOSE_LOGIN_WINDOW = 'TO_CLOSE_LOGIN_WINDOW';//关闭登陆界面
 const TO_MINUS_LOGIN_WINDOW = 'TO_MINUS_LOGIN_WINDOW';//最小化登陆界面
 const TO_EXIT_SYSTEM = 'TO_EXIT_SYSTEM';//退出系统
 const TO_SWITCH_ACCOUNT = 'TO_SWITCH_ACCOUNT';//切换账户
 const TO_CHOOSE_FILE = 'TO_CHOOSE_FILE';//切换账户

module.exports = {
    LOGIN,
    LOGIN_SUCCEED,
    LANGUAGE_CHANGE,
    TO_LANGUAGE_CHANGE,
    TO_CLOSE_LOGIN_WINDOW,
    TO_MINUS_LOGIN_WINDOW,
    TO_EXIT_SYSTEM,
    TO_SWITCH_ACCOUNT,
    TO_CHOOSE_FILE
}